name       : tealdeer
version    : 1.6.1
release    : 10
source     :
    - https://github.com/dbrgn/tealdeer/archive/refs/tags/v1.6.1.tar.gz : d42db25a56a72faec173c86192656c5381281dc197171f385fccffd518930430
license    : MIT
component  : system.utils
homepage   : https://tldr.sh/
summary    : A very fast implementation of tldr in Rust.
description: |
    A very fast implementation of tldr in Rust: Simplified, example based and community-driven man pages.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/tldr $installdir/usr/bin/tldr
    cd $workdir/completion
    install -Dm00644 bash_tealdeer $installdir/usr/share/bash-completion/completions/tldr
    install -Dm00644 fish_tealdeer $installdir/usr/share/fish/vendor_completions.d/tldr.fish
    install -Dm00644 zsh_tealdeer $installdir/usr/share/zsh/site-functions/_tealdeer
