name       : tealdeer
version    : 1.4.1
release    : 5
source     :
    - https://github.com/dbrgn/tealdeer/archive/v1.4.1.tar.gz : eaf42fe17be751985cbf46c170ef623fcbd36028c88c2e70823492a9335a4a8e
license    : MIT
component  : system.utils
homepage   : https://tldr.sh/
summary    : A very fast implementation of tldr in Rust.
description: |
    A very fast implementation of tldr in Rust: Simplified, example based and community-driven man pages.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/tldr $installdir/usr/bin/tldr
    install -Dm00644 $workdir/bash_tealdeer $installdir/usr/share/bash-completion/completions/tldr
    install -Dm00644 $workdir/fish_tealdeer $installdir/usr/share/fish/vendor_completions.d/tldr.fish
    install -Dm00644 $workdir/zsh_tealdeer $installdir/usr/share/zsh/site-functions/_tealdeer
