name       : tealdeer
version    : 1.5.0
release    : 8
source     :
    - https://github.com/dbrgn/tealdeer/archive/refs/tags/v1.5.0.tar.gz : 00902a50373ab75fedec4578c6c2c02523fad435486918ad9a86ed01f804358a
license    : MIT
component  : system.utils
homepage   : https://tldr.sh/
summary    : A very fast implementation of tldr in Rust.
description: |
    A very fast implementation of tldr in Rust: Simplified, example based and community-driven man pages.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/tldr $installdir/usr/bin/tldr
    install -Dm00644 $workdir/bash_tealdeer $installdir/usr/share/bash-completion/completions/tldr
    install -Dm00644 $workdir/fish_tealdeer $installdir/usr/share/fish/vendor_completions.d/tldr.fish
    install -Dm00644 $workdir/zsh_tealdeer $installdir/usr/share/zsh/site-functions/_tealdeer
